In [1]:
"""
Convert the USGS to COMID csv file to a USGS to NextGen WB-ID csv file.

Written by Quinn Russell
"""

import json
import pandas as pd
import geopandas as gpd

In [9]:
# read USGS to COMID file
usgs_to_comid = pd.read_csv("usgs_to_comid.csv")
usgs_to_comid.head()

,id,gage_id,comid,channel_id,timeseries_id
0,0,7227420,20001250,555bab42-b527-4e0d-a3a6-59474aed1ed3,36af5d44-7753-4dd2-86fd-dc90892e650f
1,1,7227500,19984864,555bab42-b527-4e0d-a3a6-59474aed1ed3,e6a38c63-7f62-46ea-be4f-79db951dfac2
2,2,7227890,24803965,555bab42-b527-4e0d-a3a6-59474aed1ed3,6c352775-02b9-493c-b926-1694f86239d2
3,3,7228000,19972126,555bab42-b527-4e0d-a3a6-59474aed1ed3,5c3948c1-faed-4cd5-b0ab-c6a1ad5e95a4
4,4,7233500,13837931,555bab42-b527-4e0d-a3a6-59474aed1ed3,31948a00-9f9e-421c-97e4-39b806017071

In [ ]:
hydrolocations = gpd.read_file("../3/tx_subset.gpkg", layer="hydrolocations")
hf_gages = hydrolocations[hydrolocations["hl_reference"]=="gages"]

,poi_id,id,nex_id,hf_id,hl_link,hl_reference,hl_uri,hl_source,hl_x,hl_y,vpuid,geometry
0,1630,wb-2431077,nex-2431078,806070.0,1298,resops,resops-1298,ref-fab,-153378.184965,802386.349535,12,POINT (-153378.185 802386.35)
1,4973,wb-2430581,nex-2430582,782187.0,1806,hilarri,hilarri-1806,ref-fab,-182955.068214,814752.321992,12,POINT (-182955.068 814752.322)
2,4973,wb-2430581,nex-2430582,782187.0,1360852,wbout,wbout-1360852,ref-fab,-182955.068214,814752.321992,12,POINT (-182955.068 814752.322)
3,1629,wb-2430596,nex-2430597,781883.0,1372360,wbout,wbout-1372360,ref-fab,-164629.366699,798649.842061,12,POINT (-164629.367 798649.842)
4,1630,wb-2431077,nex-2431078,806070.0,1334181,wbout,wbout-1334181,ref-fab,-153378.184965,802386.349535,12,POINT (-153378.185 802386.35)

In [11]:
gages = hf_gages["hl_uri"].to_list()
wb_ids = hf_gages["id"].to_list()
gage_ids = [int(gage[6:]) for gage in gages] # match formatting of csv
gage_to_wb = dict(zip(gage_ids, wb_ids))

In [19]:
gage_ids

[8155200,
 8158827,
 8158100,
 8158000,
 8154700,
 8155400,
 8155240,
 8158840,
 8158970,
 8158050,
 8158700,
 8154510,
 8172400,
 8154000,
 8159150,
 8157500,
 8158880,
 8158800,
 8158819,
 8158920,
 8158200,
 8158600,
 8155300,
 8158810,
 8158860,
 8156675,
 8158035,
 8158380,
 8159000,
 8156800,
 8158927]

In [12]:
usgs_to_comid["wb_id"] = usgs_to_comid["gage_id"].map(gage_to_wb).fillna("NA")

In [13]:
usgs_to_comid = usgs_to_comid[usgs_to_comid['wb_id'] != "NA"]

In [15]:
usgs_to_comid = usgs_to_comid.drop('comid', axis=1).rename(columns={'wb_id': 'comid'})

In [21]:
usgs_to_comid = usgs_to_comid.reset_index(drop=True)

In [22]:
usgs_to_comid.to_csv("tx_usgs_to_wbid.csv", index=True)